ukparliament/parliament.uk-things

app/controllers/constituencies_controller.rb, app/controllers/houses/parties_controller.rb, app/controllers/parliaments/houses/parties_controller.rb, app/views/constituencies/_constituency.html.haml, app/views/constituencies/map.html.haml, app/views/constituencies/show.html.haml, app/views/houses/parties/show.html.haml, app/views/parliaments/houses/parties/show.html.haml, app/views/people/show.html.haml, app/views/shared/_map.html.haml, spec/controllers/constituencies_controller_spec.rb, spec/controllers/houses/parties_controller_spec.rb, spec/fixtures/vcr_cassettes/ConstituenciesController/GET_show/assigns_constituency_seat_incumbencies_current_incumbency_and_party.yml, spec/views/constituencies/_constituency.html.haml_spec.rb, spec/views/people/show.html.haml_spec.rb
* Checked all files to make sure they are the same as the prototype
* Updated any differing files to make them the same
=> [WEBDEV-169] Ensure parity with prototype

Gemfile, README.md
=> [WEBDEV-142] Documentation

Gemfile.lock, app/controllers/media_controller.rb, app/views/media/show.html.haml, app/views/people/show.html.haml, config/locales/en.yml, spec/controllers/media_controller_spec.rb, spec/fixtures/vcr_cassettes/MediaController/GET_show/assigns_image.yml, spec/fixtures/vcr_cassettes/MediaController/GET_show/assigns_image_person.yml, spec/fixtures/vcr_cassettes/MediaController/GET_show/renders_the_show_template.yml, spec/fixtures/vcr_cassettes/MediaController/GET_show/should_have_a_response_with_http_status_ok_200_.yml, spec/routing/media_routing_spec.rb, spec/support/routing/shared_examples.rb, spec/views/media/show.html.haml_spec.rb
* Added media files
* Updated en.yml
* Updated spec to test media
* Implemented responsive images on media show
=> [WEBDEV-168][WEBSITE-1685] Add media + add responsive images

Gemfile, Gemfile.lock
* Added Geosparql gem to gemfile for maps
=> [WEBDEV-216] Add GeoSparql to Gemfile

app/controllers/constituencies_controller.rb, app/controllers/parties_controller.rb
* ConstituencyController#lookup_by_letters
* PartiesController#lookup_by_letters
=> [WEBDEV-213] Move lookup_by_letters methods from Things app to Lists app

Dockerfile, Gemfile, Gemfile.lock, config/application.rb
* Updated version of Puma in Gemfile to temporarily use master branch
* Added if statement for using stopgap_13632 gem
* Required Stopgap gem in application.rb
* Updated Dockerfile
=> [WEBDEV-224] IO Error

app/controllers/places_controller.rb, app/views/places/show.html.haml, config/locales/en.yml, spec/controllers/places_controller_spec.rb, spec/fixtures/vcr_cassettes/PlacesController/GET_show/assigns_place_constituencies.yml, spec/fixtures/vcr_cassettes/PlacesController/GET_show/renders_the_show_template.yml, spec/fixtures/vcr_cassettes/PlacesController/GET_show/should_have_a_response_with_http_status_ok_200_.yml
* Add places_controller
* Add views
* Add tests
=> [WEBSITE-1746] Create places/:place_id show page

app/controllers/constituencies_controller.rb
* Wrapped @current_party variable in conditional to check @current_incumbency is not nil
=> [WEBSITE-1881] No Method Error on some constituency show pages

app/views/people/show.html.haml
* Fixed bug by checking most recent incumbency is with House of Commons
=> [WEBSITE-1884] How to contact your mp showing on Lords pages

app/controllers/people_controller.rb, spec/controllers/people_controller_spec.rb, spec/fixtures/vcr_cassettes/PeopleController/GET_show/assigns_person_seat_incumbencies_committees_house_incumbencies_current_party_membership_most_recent_incumbency_and_current_incumbency.yml
* Added committees to show action
* Added specs
=> [WEBSITE-1760] Update PeopleController#show to include committees

app/views/people/show.html.haml
- Added link to current role constituency
- Enable hidden content when js is switched off
=> [WEBSITE-1926] Added link to constituency of current role

Gemfile, Gemfile.lock, app/views/people/show.html.haml, spec/views/people/show.html.haml_spec.rb
- Added feature flag for committees
- Updated pugin gem version
=> [WEBSITE-1954] Added feature flag for committees

Gemfile, Gemfile.lock, app/controllers/concerns/grouping_helper.rb, app/controllers/concerns/history_helper.rb, app/controllers/people_controller.rb, app/views/people/show.html.haml, config/locales/en.yml, spec/helpers/grouping_helper_spec.rb, spec/helpers/history_helper_spec.rb, spec/views/people/show.html.haml_spec.rb
* Added HistoryHelper, to sort roles by date
* Added GroupingHelper, to group incumbencies by role
* Added tests for HistoryHelper and GroupingHelper
* Refactored people/show timeline view
* Amended PeopleController#show to use HistoryHelper and GroupingHelper
* Amended people/show tests
* Implemented new timeline styling
=> [WEBSITE-1925][WEBSITE-1981][WEBSITE-2002] Refactor people/show timeline

app/views/people/show.html.haml, spec/views/people/show.html.haml_spec.rb
=> [Fix] Correct rendering on people/show when only one parliamentary role

app/views/people/show.html.haml
=> [Fix] Additional fix for single parliamentary role

app/views/people/show.html.haml
* added conditional to view - timeline only shows for people who have previous roles
=> [WEBSITE-2052] Don't show timeline for people with only current roles

app/controllers/concerns/grouping_helper.rb, app/views/people/show.html.haml
* Changed - on previous consitutencies to 'to'
* Updated helper to use 'grouping_methods' instead of 'optional_methods' for clarity
=> [WEBSITE-2059] Change - to 'to' and refactor

Gemfile.lock, app/controllers/people_controller.rb, app/views/people/show.html.haml, config/locales/en.yml, spec/controllers/people_controller_spec.rb, spec/fixtures/vcr_cassettes/PeopleController/GET_show/assigns_person_seat_incumbencies_committee_memberships_house_incumbencies_government_incumbencies_current_party_membership_most_recent_incumbency_and_current_incumbency.yml, spec/views/people/show.html.haml_spec.rb
* Added government roles to people controller
* Added government roles to people show view
* Added tests for people show
* Added tests for people controller
=> [WEBSITE-2029] Add government roles

Gemfile, Gemfile.lock, spec/fixtures/vcr_cassettes/ConstituenciesController/GET_map/assigns_constituency.yml, spec/fixtures/vcr_cassettes/ConstituenciesController/GET_map/renders_the_map_template.yml, spec/fixtures/vcr_cassettes/ConstituenciesController/GET_map/request_JSON/assigns_constituency.yml, spec/fixtures/vcr_cassettes/ConstituenciesController/GET_map/request_JSON/constituency_is_not_current/will_respond_with_ActionController_RoutingError.yml, spec/fixtures/vcr_cassettes/ConstituenciesController/GET_map/request_JSON/renders_the_map_template.yml, spec/fixtures/vcr_cassettes/ConstituenciesController/GET_map/request_JSON/should_have_a_response_with_a_http_status_ok_200_.yml, spec/fixtures/vcr_cassettes/ConstituenciesController/GET_map/should_have_a_response_with_a_http_status_ok_200_.yml, spec/fixtures/vcr_cassettes/ConstituenciesController/GET_show/given_a_valid_postcode/assigns_postcode_postcode_constituency.yml, spec/fixtures/vcr_cassettes/ConstituenciesController/GET_show/given_an_invalid_postcode/assigns_postcode_and_flash_error_.yml, spec/fixtures/vcr_cassettes/ConstituenciesController/GET_show/variable_assignment/assigns_constituency_seat_incumbencies_current_incumbency_party_and_regions.yml, spec/fixtures/vcr_cassettes/ConstituenciesController/GET_show/variable_assignment/assigns_current_incumbency_to_be_the_current_incumbency.yml, spec/fixtures/vcr_cassettes/ConstituenciesController/GET_show/variable_assignment/assigns_party.yml, spec/fixtures/vcr_cassettes/ConstituenciesController/GET_show/variable_assignment/assigns_regions_to_an_empty_array_if_no_regions_are_available.yml, spec/fixtures/vcr_cassettes/ConstituenciesController/GET_show/variable_assignment/assigns_regions_when_available.yml, spec/fixtures/vcr_cassettes/ConstituenciesController/GET_show/variable_assignment/assigns_seat_incumbencies_in_reverse_chronological_order.yml, spec/fixtures/vcr_cassettes/ConstituenciesController/GET_show/variable_assignment/renders_the_show_template.yml, spec/fixtures/vcr_cassettes/ConstituenciesController/GET_show/variable_assignment/should_have_a_response_with_a_http_status_ok_200_.yml, spec/fixtures/vcr_cassettes/ConstituenciesController/_data_check/an_unavailable_data_format_is_requested/should_raise_ActionController_UnknownFormat_error.yml, spec/fixtures/vcr_cassettes/ContactPointsController/GET_show/assigns_contact_point.yml, spec/fixtures/vcr_cassettes/ContactPointsController/GET_show/download/should_download_a_vcard_attachment.yml, spec/fixtures/vcr_cassettes/ContactPointsController/GET_show/should_have_a_response_with_a_http_status_ok_200_.yml, spec/fixtures/vcr_cassettes/PeopleController/GET_show/assigns_person_seat_incumbencies_committee_memberships_house_incumbencies_government_incumbencies_current_party_membership_most_recent_incumbency_and_current_incumbency.yml, spec/fixtures/vcr_cassettes/PeopleController/GET_show/given_a_valid_postcode/assigns_postcode_postcode_constituency.yml, spec/fixtures/vcr_cassettes/PeopleController/GET_show/given_an_invalid_postcode/assigns_postcode_and_flash_error_.yml, spec/fixtures/vcr_cassettes/PeopleController/GET_show/renders_the_show_template.yml, spec/fixtures/vcr_cassettes/PeopleController/GET_show/should_have_a_response_with_http_status_ok_200_.yml
* Replaced old ontology with new version. For example Incumbency =>
ParliamentaryIncumbency
* Updated parliament-grom-decorators and parliament-utils gems
=> Updated parliament-grom-decorators for new ontology

Gemfile, Gemfile.lock, app/views/people/show.html.haml, spec/views/people/show.html.haml_spec.rb
* Updated parliament-grom-decorators
* Updated people/show view to use #current_mp? and #current_lord?
* Updated specs
=> Updated parliament-grom-decorators version

Gemfile, Gemfile.lock, app/views/people/_related_links.html.haml, app/views/people/show.html.haml, config/locales/en.yml, spec/views/people/related_links.html.haml_spec.rb, spec/views/people/show.html.haml_spec.rb
- [WEBSITE-1657] Added members web links
- [WEBSITE-1945] Added spec for related links
- Updated parliament-grom-decorators gem version
=> [WEBSITE-1657][WEBSITE-1945] Added members web links and spec

app/controllers/concerns/role_helper.rb, app/controllers/people_controller.rb, app/views/constituencies/map.html.haml, app/views/constituencies/show.html.haml, app/views/houses/parties/show.html.haml, app/views/people/_current_role.html.haml, app/views/people/_current_roles.html.haml, app/views/people/_timeline_role.html.haml, app/views/people/_timeline_roles.html.haml, app/views/people/show.html.haml, spec/helpers/role_helper_spec.rb, spec/views/people/show.html.haml_spec.rb
* Amended _current_roles partial
* Added additional tests
=> [WEBSITE-2136] Order current roles on people/show page by type

Gemfile, Gemfile.lock, app/controllers/people_controller.rb, app/views/people/_current_roles.html.haml, app/views/people/_timeline_roles.html.haml, config/locales/en.yml, spec/controllers/people_controller_spec.rb, spec/views/people/show.html.haml_spec.rb
* Updated parliament-grom-decorators gem
* Added opposition roles to PeopleController
* Added opposition roles to people show view and partials
* Updated i18n locales
* Updated view and controller specs
=> [WEBSITE-1365][WEBSITE-1366] Add Opposition Roles to People Show

app/views/constituencies/_member_info.html.haml, app/views/constituencies/map.html.haml, app/views/constituencies/show.html.haml, app/views/houses/parties/show.html.haml, app/views/houses/show.html.haml, app/views/media/show.html.haml, app/views/parliaments/houses/parties/show.html.haml, app/views/parliaments/houses/show.html.haml, app/views/parliaments/parties/show.html.haml, app/views/parliaments/show.html.haml, app/views/parties/show.html.haml, app/views/people/_when_to_contact.html.haml, app/views/people/show.html.haml, app/views/postcodes/_postcode_lookup.html.haml
I've ignored the *hybrid_bills* directory. @vinternet-pds will do the standardisation on *hybrid_bills* to keep our commits clean.
=> [WEBDEV-433] Refactor application of HTML attributes in HAML

Gemfile, Gemfile.lock, app/controllers/constituencies_controller.rb, app/controllers/contact_points_controller.rb, app/controllers/houses/parties_controller.rb, app/controllers/houses_controller.rb, app/controllers/media_controller.rb, app/controllers/parliaments/houses/parties_controller.rb, app/controllers/parliaments/houses_controller.rb, app/controllers/parliaments/parties_controller.rb, app/controllers/parliaments_controller.rb, app/controllers/people_controller.rb, app/controllers/places_controller.rb
*Refactored controller actions to use Parliament::Utils::Helper:FilterHelper to use #filter and #filter_sort to handle requests
=> [WEBDEV-311] Refactored things controllers to use FilterHelper

Gemfile, Gemfile.lock, app/controllers/people_controller.rb, app/views/people/_current_roles.html.haml, app/views/people/_timeline_roles.html.haml, spec/controllers/people_controller_spec.rb, spec/fixtures/vcr_cassettes/PeopleController/GET_show/assigns_person_seat_incumbencies_committee_memberships_government_incumbencies_current_party_membership_most_recent_incumbency_and_current_incumbency.yml, spec/views/people/show.html.haml_spec.rb
* Updated parliament-grom-decorators
* Removed house incumbencies
* Added additional conditionals to views to check for members
* Updated specs
=> Updated parliament-grom-decoratos and removed house incumbencies

Gemfile, Gemfile.lock, app/controllers/articles_controller.rb, app/controllers/concerns/markdown_helper.rb, app/views/articles/show.html.haml, spec/controllers/articles_controller_spec.rb, spec/controllers/constituencies_controller_spec.rb, spec/controllers/contact_points_controller_spec.rb, spec/controllers/houses/parties_controller_spec.rb, spec/controllers/houses_controller_spec.rb, spec/controllers/media_controller_spec.rb, spec/controllers/parliaments/houses/parties_controller_spec.rb, spec/controllers/parliaments/houses_controller_spec.rb, spec/controllers/parliaments/parties_controller_spec.rb, spec/controllers/parliaments_controller_spec.rb, spec/controllers/parties_controller_spec.rb, spec/controllers/people_controller_spec.rb, spec/controllers/places_controller_spec.rb, spec/fixtures/vcr_cassettes/ArticlesController/GET_show/variable_assignment/when_successful/assigns_article_as_a_Grom_Node.yml, spec/fixtures/vcr_cassettes/ArticlesController/GET_show/variable_assignment/when_successful/assigns_article_as_a_Grom_Node_of_type_Article.yml, spec/fixtures/vcr_cassettes/ArticlesController/GET_show/variable_assignment/when_successful/assigns_article_to_the_article_with_correct_id.yml, spec/fixtures/vcr_cassettes/ArticlesController/GET_show/variable_assignment/when_successful/should_have_a_response_with_a_http_status_ok_200_.yml, spec/fixtures/vcr_cassettes/ArticlesController/GET_show/variable_assignment/when_unsuccessful/should_raise_ActionController_RoutingError_error.yml, spec/fixtures/vcr_cassettes/ArticlesController/_data_check/an_unavailable_data_format_is_requested/should_raise_ActionController_UnknownFormat_error.yml, spec/helpers/markdown_helper_spec.rb, spec/support/controllers/shared_examples.rb
* Add ArticlesController#show method
* Add articles/show view
* Add MarkdownHelper to transform markdown into HTML
* Requiring 'redcarpet' gem to transform markdown into HTML
* Updated parliament-routes gem version
* Updated parliament-grom-decorators gem version
* Add tests
* DRY up #data_check tests to use shared examples
=> Guide To Procedure - Articles Controllers, Views, Tests

app/views/hybrid_bills/show.haml, app/views/hybrid_bills/steps/writing-your-petition-online.haml
-   correcting step names in views to reflect changes
=> correcting step names in views to reflect changes

app/views/parliaments/houses/parties/show.html.haml, app/views/parliaments/houses/show.html.haml, app/views/parliaments/parties/show.html.haml, app/views/parliaments/show.html.haml, spec/views/parliaments/houses/parties/show.html.haml_spec.rb, spec/views/parliaments/houses/show.html.haml_spec.rb, spec/views/parliaments/parties/show.html.haml_spec.rb, spec/views/parliaments/show.html.haml_spec.rb
Ensure correct use of MPs and Lords across pages, where required
=> Add tests for parliaments view pages

Gemfile, Gemfile.lock, app/controllers/articles_controller.rb, app/controllers/concepts_controller.rb, app/views/articles/show.html.haml, app/views/concepts/show.html.haml, spec/controllers/concepts_controller_spec.rb, spec/fixtures/vcr_cassettes/ConceptsController/GET_show/variable_assignment/when_successful/assigns_concept_as_a_Grom_Node.yml, spec/fixtures/vcr_cassettes/ConceptsController/GET_show/variable_assignment/when_successful/assigns_concept_as_a_Grom_Node_of_type_Article.yml, spec/fixtures/vcr_cassettes/ConceptsController/GET_show/variable_assignment/when_successful/assigns_concept_to_the_article_with_correct_id.yml, spec/fixtures/vcr_cassettes/ConceptsController/GET_show/variable_assignment/when_successful/should_have_a_response_with_a_http_status_ok_200_.yml, spec/fixtures/vcr_cassettes/ConceptsController/GET_show/variable_assignment/when_unsuccessful/should_raise_ActionController_RoutingError_error.yml, spec/fixtures/vcr_cassettes/ConceptsController/_data_check/an_unavailable_data_format_is_requested/should_raise_ActionController_UnknownFormat_error.yml
* Add controller code for Concepts
* Add tests
* Update parliament-routes, parliament-grom-decorators and pugin versions
* Updates to articles/show view
=> GTP - Concept show page

app/views/people/_current_roles.html.haml, app/views/people/_related_links.html.haml, app/views/people/_timeline_roles.html.haml, app/views/people/show.html.haml, config/locales/en.yml, spec/views/people/related_links.html.haml_spec.rb, spec/views/people/show.html.haml_spec.rb
* reduce number of names displayed for lord
* change house of lords role to parliamentary role
* change media link name
* Update party/group membership display
=> [Amend-Lords-Pages] Amend lords pages

Gemfile, Gemfile.lock, app/controllers/articles_controller.rb, app/controllers/collections_controller.rb, app/views/articles/show.html.haml, app/views/collections/show.html.haml, config/locales/en.yml, spec/controllers/collections_controller_spec.rb, spec/fixtures/vcr_cassettes/CollectionsController/GET_show/variable_assignment/when_successful/assigns_collection_as_a_Grom_Node.yml, spec/fixtures/vcr_cassettes/CollectionsController/GET_show/variable_assignment/when_successful/assigns_collection_as_a_Grom_Node_of_type_Collection.yml, spec/fixtures/vcr_cassettes/CollectionsController/GET_show/variable_assignment/when_successful/assigns_collection_to_the_article_with_correct_id.yml, spec/fixtures/vcr_cassettes/CollectionsController/GET_show/variable_assignment/when_successful/should_have_a_response_with_a_http_status_ok_200_.yml, spec/fixtures/vcr_cassettes/CollectionsController/GET_show/variable_assignment/when_unsuccessful/should_raise_ActionController_RoutingError_error.yml, spec/fixtures/vcr_cassettes/CollectionsController/_data_check/an_unavailable_data_format_is_requested/should_raise_ActionController_UnknownFormat_error.yml, spec/views/articles/show.html.haml_spec.rb, spec/views/collections/show.html.haml_spec.rb
* Create show method for CollectionsController, with tests and view
* Amend ArticlesController to include Collections that article belongs to
* Update parliament-routes and parliament-grom-decorator gems
=> GTP - Collections

app/models/hybrid_bill.rb, config/locales/en.yml
* Updated model to reflect petitioning window changes
* Updated translations for Additional Provision
=> Hybrid Bills - Additional Provision updates

Gemfile.lock
- Release to include missing commits
=> [RELEASE] Pugin version bump
